name: CI
on:
  push:
    branches:
      - master
      - dev 
  pull_request:

permissions:
  contents: read 

jobs:
  lint-go:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.61'

  lint-vue:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd webui && bun i
      - run: cd webui && bun x prettier ./src --check
  
  test-vue:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd webui && bun i
      - run: make web-test

  test-go:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - run: 'go test -v ./...'
