name: Publish to GH Pages

on:
  push:
    branches: ['master']

  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd webui && bun i && cd -
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: |
          env PATH="$(go env GOPATH)/bin:$PATH" make web
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with: 
          path: './webui/dist'
      - id: publish
        uses: actions/deploy-pages@v4

